const express = require("express");
const router = express.Router();
const Services = require("../models/Services");
const Employees = require("../models/Employees");

// get all the services and employees in one page with nif optionally needed (if specified any value in nif it will be considered true)
// examples 1: http://localhost:3000/servicesAndEmployees/5/2
// examples 2: http://localhost:3000/servicesAndEmployees/5/2/true (only nif)
router.get("/servicesAndEmployees/:nEmployees/:nServices/:nif?", (req, res, next) => {
  let allServices;

  // let's find all the services, limited to a number that gets passed in the URL
  Services.find()
    .limit(+req.params.nServices)
    .then(allServicesPayload => {
      allServices = allServicesPayload;
      // let's find all the employees, limited to a number that gets passed in the URL
      return Employees.find().limit(+req.params.nEmployees);
    })
    .then(allEmployees => {
      let hbsPayload = {
        services: allServices,
        employees: allEmployees
      };

      if (req.params.nif !== undefined) {
        hbsPayload.showOnlyNIF = true;
      }

      // let's create the data that gets passed into the view
      res.render("servicesAndEmployees", hbsPayload);
    });
});

// find a service by nif: http://localhost:3000/servicesByNIF/14757F (this nif must exist in your database)
router.get("/servicesByNIF/:nif", (req, res, next) => {
  Services.find({ nif: req.params.nif }).then(service => {
    res.render("servicesAndEmployees", {
      services: service
    });
  });
});

// this renders the form for the "servicesByNIFQS" endpoint
router.get("/checkNIF", (req, res) => {
  res.render("searchByNIF");
});

// this consumes the querystring generated by the form in the "checkNIF" endpoint
router.get("/servicesByNIFQS", (req, res, next) => {
  console.log(req.query);

  Services.find({ nif: req.query.nif }).then(service => {
    res.render("servicesAndEmployees", {
      services: service
    });
  });
});

// this consumes the querystring generated by the form in the "checkNIF" endpoint
router.get("/services", (req, res, next) => {
  Services.find()
    .sort({ createdAt: -1 })
    .then(service => {
      res.render("servicesAndEmployees", {
        services: service
      });
    });
});

// display a map from a city and street, passing in the values in the URL using a querystring
// http://localhost:3000/getMap?city=bcn&street=carrer+tallers
router.get("/getMap", (req, res, next) => {
  const cityPayload = req.query.city.toUpperCase();
  const streetPayload = req.query.street;

  res.render("map", {
    city: cityPayload,
    street: streetPayload
  });
});

// render a form that allows you to create a new service
router.get("/createService", (req, res) => {
  res.render("createService");
});

// endpoint that records a new post sent by the form in createService.hbs
router.post("/createServicePOST", (req, res) => {
  Services.create({
    name: req.body.name,
    category: req.body.category,
    nif: req.body.nif
  }).then(() => {
    res.redirect("/services");
  });
});

router.get("/updateUser/:id", (req, res) => {
  Employees.findById(req.params.id).then(employee => {
    console.log(employee);
    res.render("updateUser", { employee });
  });
});

router.post("/updateUser", (req, res) => {
  Employees.findByIdAndUpdate(
    req.body.id,
    {
      name: req.body.name
    },
    { new: true }
  ).then(employee => {
    res.redirect("/servicesAndEmployees/5/2");
    // res.render(`updateUser/${req.body.id}`, { employee });
  });
});

module.exports = router;
